---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: lidarr
  name: lidarr
spec:
  ports:
    - name: "8686"
      port: 8686
      targetPort: 8686
  selector:
    io.kompose.service: lidarr

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: lidarr
  name: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lidarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/htpc-download-box-default: "true"
        io.kompose.service: lidarr
    spec:
      containers:
        - env:
            - name: PGID
            - name: PUID
            - name: TZ
          image: linuxserver/lidarr:latest
          name: lidarr
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /config
              name: config
            - mountPath: /music
              name: music
            - mountPath: /downloads
              name: downloads
      restartPolicy: Always
      volumes:
        - name: config
          hostPath:
            path: /mnt/mac/Users/segiddins/.config/lidarr
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: music
          hostPath:
            path: /mnt/mac/Volumes/Media/Music
        - name: downloads
          hostPath:
            path: /mnt/mac/Volumes/docker/htpc-download-box/downloads
