---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: overseerr
  name: overseerr
spec:
  ports:
    - name: "5055"
      port: 5055
      targetPort: 5055
  selector:
    io.kompose.service: overseerr

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: overseerr
  name: overseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: overseerr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/htpc-download-box-default: "true"
        io.kompose.service: overseerr
    spec:
      containers:
        - env:
            - name: LOG_LEVEL
              value: debug
            - name: TZ
              value: America/Los_Angeles
          image: sctx/overseerr:latest
          name: overseerr
          ports:
            - containerPort: 5055
              hostPort: 5055
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config
              name: overseerr-claim0
      restartPolicy: Always
      volumes:
        - name: config
          hostPath:
            # Mac filesystem is mounted as /mnt/mac
            path: /mnt/mac/Volumes/docker/htpc-download-box/config/overseerr
            type: Directory # this field is optional
