---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: readarr-ebooks
  name: readarr-ebooks
spec:
  ports:
    - name: "8787"
      port: 8787
      targetPort: 8787
  selector:
    io.kompose.service: readarr-ebooks

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: readarr-ebooks
  name: readarr-ebooks
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: readarr-ebooks
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/htpc-download-box-default: "true"
        io.kompose.service: readarr-ebooks
    spec:
      containers:
        - env:
            - name: PGID
            - name: PUID
            - name: TZ
          image: linuxserver/readarr:develop
          name: readarr-ebooks
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /config
              name: config
            - mountPath: /books
              name: ebooks
            - mountPath: /Volumes/Scratch/downloads
              name: downloads
            - mountPath: /todo
              name: todo
      restartPolicy: Always
      volumes:
        - name: config
          hostPath:
            path: /mnt/mac/Users/segiddins/.config/readarr-ebooks
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: ebooks
          hostPath:
            path: /mnt/mac/Volumes/Storage/Media/eBooks
        - name: downloads
          hostPath:
            path: /mnt/mac/Volumes/Scratch/downloads
        - name: todo
          hostPath:
            path: /mnt/mac/Volumes/Storage/Books
