---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  ports:
    - name: "8989"
      port: 8989
      targetPort: 8989
  selector:
    io.kompose.service: sonarr

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/htpc-download-box-default: "true"
        io.kompose.service: sonarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "100"
            - name: PUID
              value: "1026"
            - name: TZ
              value: "America/Los_Angeles"
          image: linuxserver/sonarr:latest
          name: sonarr
          volumeMounts:
            - mountPath: /etc/localtime
              readOnly: true
              name: localtime
            - mountPath: /config
              name: config
            - mountPath: /tv
              name: tv
            - mountPath: /downloads
              name: downloads
      restartPolicy: Always
      volumes:
        - name: config
          hostPath:
            path: /mnt/mac/Users/segiddins/.config/sonarr
        - name: tv
          hostPath:
            path: /mnt/mac/Volumes/Media/TV
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: downloads
          hostPath:
            path: /mnt/mac/Volumes/docker/htpc-download-box/downloads
